### ISSUE TITLE
CategoryListAdaptor (null reference hatası)

### ISSUE THREAD

**Issue by erdembingol** [erdembingol/EMUA#29]
Mustafa,

37. satırda 2 kere null reference hatası aldım. Gerçi şuanda satır aynı değildir kod içinde biraz düzenleme yaptım. Neyse 'itemname' değerini parçalamadan önce kontrol et 2 kere bu yüzden null reference hatası aldım.

**Comment by erdembingol** [comment]
Satır numarası yanlış gitmiş onu dikkate alma açıklmaya bakarsın

**Comment by mustafasubasi** [comment]
Merhaba Erdem.
Sorun servisten response gelmemesinden kaynaklanıyor. Geçici bir problemdir.
Ama hata kontrol için ayrı bir çalışma planlayacağız.

İyi çalışmalar.
